# Generated by Django 3.0.1 on 2019-12-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191230_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_pages',
            new_name='pages_img',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_sample',
            new_name='sample_url',
        ),
    ]
