# Generated by Django 3.0.1 on 2019-12-30 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20191230_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'PluralForMyModel'},
        ),
    ]
